### ISSUE TITLE
/bin/sh: 1: ameba: not found

### ISSUE THREAD

**Issue by MatheusRich** [crystal-ameba/vscode-crystal-ameba#6]
After installing the extension this warning appeared `/bin/sh: 1: ameba: not found`. I'm using ameba as a dependency of my project.
```
Crystal 0.34.0 [4401e90f0] (2020-04-06)

LLVM: 8.0.0
Default target: x86_64-unknown-linux-gnu

Shards 0.10.0 [4091ac5] (2020-04-06)
```

**Comment by MatheusRich** [comment]
Running `sudo cp ./bin/ameba /usr/bin` from my project dir did the trick

**Comment by veelenga** [comment]
Yeah, so right now to let it work you need to install Ameba binary first which is available globally.

But yeah, the plugin should check `<project_root>/bin/ameba` first and afterward try to execute a global binary.

**Comment by MatheusRich** [comment]
Any chance to let this be a config?

**Comment by petr-fischer** [comment]
This issue is closed, but it's still not ideal - if you have some Crystal project with ameba and some projects without ameba (in dependencies), you just don't want to run ameba binary at all in the projects without ameba dependency. So the warning "/bin/sh: 1: ameba: not found" is very annoying (after each file save operation) in vscode for that projects without ameba support. Note: best solution for me is to uninstall ameba vscode plugin completely (for now) :(

**Comment by veelenga** [comment]
Should be closed by https://github.com/crystal-ameba/vscode-crystal-ameba/issues/12
